### ISSUE TITLE
Rare crashes on respawn

### ISSUE THREAD

**Issue by up-left** [youkaicountry/yknytt#100]
Sometimes the game crashes on respawn without any message. Chance to catch this increases in heavy-loaded screens like this (Sky Flower x1000y986):

![изображение](https://user-images.githubusercontent.com/36682563/101064900-1579cd00-35c7-11eb-819c-5dcc4cb391a5.png)

Here it happens on about 10% of all respawns.

**Comment by youkaicountry** [comment]
There is probably a race condition lurking somewhere and more things need to be deferred. Bugs like this area always so hard to hunt down :)

**Comment by youkaicountry** [comment]
I believe this was solved with the reversion to single-threaded physics.

 Code would need to be cleaned up significantly to not interact with physics parameters from outside of the physics step. I suspect many of the asyncs we are using end up modifying physics parameters from outside, and it would be a rather large refactor that probably wouldn't even buy us much (if any) performance increases anyhow.

Closing this for now.
