### ISSUE TITLE
Level downloading

### ISSUE THREAD

**Issue by up-left** [youkaicountry/yknytt#101]
Since manual level download looks outdated, it's better to implement in-game downloading.

**Comment by up-left** [comment]
I hope to work on this next time.

**Comment by youkaicountry** [comment]
This is a really good idea. I would suggest replacing "Install Level" with "Download level". (Since this can directly run `.knytt.bin` files, there really isn't a need for it as a main menu button anymore. A separate command-line tool for power users, perhaps.)

**Comment by up-left** [comment]
Some unimplemented ideas:
- Waiting animation in LevelSelection, because server response can take a long time.
- Also it's not obvious that LevelSelection has auto-load "infinite" scroll. Maybe place empty buttons there in advance?
- Compress Icon.png-s in worlds-parser, because some of them can inflate server response
- Implementation have brought some technical debt. For example, KnyttWorldManager<Texture>.WorldEntry and GameButtonInfo has the same roles. KnyttWorld.setDirectory is called first time for the first parameter, and second time for the second one.
- If a server gives away html page with code 200 instead of .knytt.bin file, the game will crash
- Uninstall level button (!)
- Also cleanup unfinished downloads (.part files) if the game crashed during download (not so necessary)
- Adding remote levels one by one in every frame is not the best decision
- Google Form to compain about broken levels

**Comment by up-left** [comment]
Also, don't forget to enable "Internet" permission before exporting for Android!

**Comment by up-left** [comment]
Almost all important features (included listed above) have been implemented. Closing as resolved.
