### ISSUE TITLE
Rescue saves from mobile devices

### ISSUE THREAD

**Issue by up-left** [youkaicountry/yknytt#116]
There must be a way to save saves from mobile device with closed filesystem to continue playing them on another device.

**Comment by youkaicountry** [comment]
The console commands `save copy` or `pass copy` should allow this, the resulting clipboard contents then are able to be pasted somewhere accessible on another machine. Does this satisfy this issue?

**Comment by up-left** [comment]
Yes, quite satisfying. I have an idea to send a save to the server and show a number to a player. After entering this number on another device, a player can continue playing a level. But that should be other issue.
