### ISSUE TITLE
Make "Optimize" button for a level

### ISSUE THREAD

**Issue by up-left** [youkaicountry/yknytt#120]
The idea is to improve game performance. Currently I see two things that can be optimized:
- Compile tilesets with GDKnyttAssetManager.compileInternalTileset
- Unpack a level to the filesystem (may help for ~100MB levels on mobile devices)

**Comment by up-left** [comment]
I've made this button, but it is still an object for discussion.
Should it be called every time after download?
Is there any other things to optimize?
Unpacking a level really helps on old mobile devices, but should it be called in every case?
Also there is no waiting animation, it just freezes the application.

**Comment by youkaicountry** [comment]
Current behavior seems reasonable, reopen if not!
