### ISSUE TITLE
Push out Juni from tiles

### ISSUE THREAD

**Issue by up-left** [youkaicountry/yknytt#122]
If Juni gets stuck in tiles, the original game slowly pushes her up.
It would be great if YKnytt had this behaviour.
Also, in "A Knytt in Time" it's a trick to emulate shift delay. The level will not work without it.

**Comment by up-left** [comment]
Could you please decrease collision area for this? Juni gets stuck too often in uneven tiles, for example, in Don't eat the mushroom green tiles, or Riku Island tiles.

**Comment by up-left** [comment]
I made it, testing for now.

**Comment by youkaicountry** [comment]
Great, thanks. Is it working better now?

**Comment by up-left** [comment]
Yes, seems acceptable.
