### ISSUE TITLE
Create 0.3.0 release

### ISSUE THREAD

**Issue by youkaicountry** [youkaicountry/yknytt#123]
I'm going to publish to 3rd release finally. It seems reasonably stable with the recent polishing and work. I'm not going to worry too much about the level downloads that don't work for now, that doesn't necessarily need to be timed perfectly with the actual release. 

The changelog should be updated first too, of course.

**Comment by youkaicountry** [comment]
Instead of listing contributor's names exhaustively by each changelog item, I'll just list the people who contributed commits to the version.

**Comment by up-left** [comment]
I don't have anything to add to the release. Later server update may break level ratings and icons, but I don't think it's a big issue.

**Comment by youkaicountry** [comment]
I've made the release and added Windows Linux and OSX binaries. For some reason Android isn't building for me, something bitrotted with my Android configuration. I'll try to figure that out soon.

Feel free to make posts about the new release wherever you want :)
