### ISSUE TITLE
Tweak Juni movement

### ISSUE THREAD

**Issue by up-left** [youkaicountry/yknytt#125]
A thread about Juni reaching places she shouldn't, and not reaching places she was supposed to.

**Comment by up-left** [comment]
Shipwrecked, x996y1006: Juni can jump to the red ball
![изображение](https://user-images.githubusercontent.com/36682563/105708380-f6ecde00-5f46-11eb-8820-5dbe6b6dc0f2.png)

**Comment by up-left** [comment]
The Great Race, x1026y996, all balls and umbrella: Juni wants to reach the left wall with pink grass by double jump and umbrella, but jumps too high and bumps her head by spikes.
![изображение](https://user-images.githubusercontent.com/36682563/105709667-9fe80880-5f48-11eb-9d4d-22aba28c908c.png)

**Comment by up-left** [comment]
The Great Race, x1044y999, all balls + umbrella: passing through this screen is surprisingly hard, umbrella doesn't carry Juni such distances
![изображение](https://user-images.githubusercontent.com/36682563/105710970-73cd8700-5f4a-11eb-8aa5-a5bddb833295.png)

**Comment by youkaicountry** [comment]
Great list, I will spend some more time tweaking Juni's physics soon.

**Comment by youkaicountry** [comment]
Juni's physics have been significantly tweaked since this issue was created, and these instances are resolved.
