### ISSUE TITLE
Compatibility document

### ISSUE THREAD

**Issue by youkaicountry** [youkaicountry/yknytt#126]
Either as a file in the docs directory or a wiki page on github, it seems like a good time to keep a compatibility list of Knytt Stories worlds. List whether or not they are able to be completed, and what issues are encountered.

**Comment by up-left** [comment]
Great! You can create this wiki page and I'll put down my notes there.

**Comment by youkaicountry** [comment]
I put up a wiki page. Worlds are arranged into 3 categories right now based on how playable they are. I'll add more entries tonight from my own notes as well.

**Comment by youkaicountry** [comment]
Document has been started, let's continue to update it as we play. Closing this issue.
