### ISSUE TITLE
Optimize local level selection

### ISSUE THREAD

**Issue by youkaicountry** [youkaicountry/yknytt#133]
Paginate locals level metadata loading similar to the level download mode, and cache local level metadata.

**Comment by up-left** [comment]
Cache is already implemented, and level loading is pretty fast. Do you think delay can be significant?
If so, there is multithreaded loading that could be fixed. If not, this screen can use only single-threaded loading.

**Comment by youkaicountry** [comment]
Ah, I do only notice it when I have a ridiculous number of local levels. 
Fixing and reimplementing the multithreaded loading would probably solve it. I'll take a look at that code again at some point.

**Comment by youkaicountry** [comment]
Resolved.
