### ISSUE TITLE
Proper Sound Effects - Request

### ISSUE THREAD

**Issue by Lt-knb** [youkaicountry/yknytt#166]
You are currently using the low-quality sound effects from KSDS. Also, Flower Bullet Hit and Flower Bullet Shot (used by objects 1, 2, and 5 of bank 9) are missing.
Please implement the original high-quality sound effects: [KS SFX.zip](https://github.com/youkaicountry/yknytt/files/9464835/KS.SFX.zip)
They were extracted from the source.

Please mind the following differences in filenames:

Big Bullet Split       = Bullet Split
Big Cannon Shot        = Cannon Shot
Knytt Climb (troupe)   = Climb
Knytt Double Jump      = Double Jump
Knytt Jump (troupe)    = Jump
Knytt Land (troupe)    = Land
Knytt Run (troupe)     = Run
Knytt Slide            = Slide
Knytt Walk (troupe)    = Walk
Liquid Shooter         = Liquid
Mega Split Bullet Shot = Mega Split
Right Combination      = Right Comb
Roller Shot A          = Roller A
Roller Shot B          = Roller B
Roller Shot Hit        = Roller Hit
Self Dropper Land      = Selfdrop
Tri Bullet Shot A      = Tri Bullet Shot

**Comment by Lt-knb** [comment]
Edit: Removed unnecessary data, added s_Nifflas_hurt (used by the Alternate Death feature in KS+), added list of filename differences

**Comment by up-left** [comment]
This requires some code changes (removing RawAudioPlayer2D and rewriting its cache), so it will be done a little bit later.
Thank you for participating!

**Comment by up-left** [comment]
Audiofiles were replaced, so the game should sound better now.
I don't close it because I will take a look at bank 9 sounds later.

**Comment by up-left** [comment]
Since the main issue was resolved, I'm closing it.
