### ISSUE TITLE
Game Freezes When Activating Save Point on Android

### ISSUE THREAD

**Issue by madrabbit90** [youkaicountry/yknytt#168]
Music still plays, but screen and controls are unresponsive and forces app restart.

**Comment by up-left** [comment]
Hmm, have no ideas why this happens.
Is it true for every level?
What version of Android do you have?
Can you play a level for a few minutes without savepoints?

**Comment by madrabbit90** [comment]
Yes, every level, unfortunately. I'm running 32-bit android 12. Otherwise runs great until the checkpoint issue. When I restart the app, it puts me back at the savepoint, so it does save before freezing.

**Comment by madrabbit90** [comment]
For some reason, though, running YKnytt through Octopus Keymapper bypassed the freeze issue. Not an ideal workaround, though, since keymappers intercept inputs and you can't use gamepad bindings as intended.

**Comment by madrabbit90** [comment]
The touchpad works fine, no issues. All the functions work. Touch input even works when mapping gamepad to touch.

**Comment by madrabbit90** [comment]
So, some consistent results:

I can now "fix" the problem by closing the app in recents, force stopping it in app settings, restarting, then activate the exact same checkpoint that froze the game last time. Game continues as normal and I won't have any more freezes for the entire play session, even across levels... ...and this seems to work every time.

So to speed up the process, I made a launch script that force stops the app package before launching the activity and that seems to mitigate the issue somewhat.

**Comment by up-left** [comment]
Still can't figure this issue out. My first thought was that the gamepad down button has UI meaning (allows you to move between controls) and interferes with in-game meaning. But that doesn't seem to be true, as in your case there is no difference between first and second run.
Writing to the file system is also not the cause, as there is no difference between saving with the gamepad down button and saving with the touchpad.
If I get any new ideas, I'll post them here!

**Comment by madrabbit90** [comment]
Another possible clue:

The temporary fix only works if Juni is dead-center on the checkpoint. If you try to activate the checkpoint any other way, the game still freezes.

**Comment by up-left** [comment]
I've made a change which may help. Expect it in 0.5.1 at the end of this week.

**Comment by up-left** [comment]
Could you please test this on the new version?

**Comment by madrabbit90** [comment]
It works! No more freezes, and so far, no side-effects. What was the solution?

**Comment by up-left** [comment]
I disabled logging after saving =) Your observation that the game saves before freezing was helpful!
