### ISSUE TITLE
cutscene page buttons should be smaller or transparent

### ISSUE THREAD

**Issue by ncrecc** [youkaicountry/yknytt#173]
some cutscenes in KS levels have text positioned around the original cutscene page buttons.
in the "Stay" ending of _canteven - Get focus_, text in numerous pages is positioned to be right above where the next page button would be. in yknytt, it is blocked, due to the buttons being larger. (the text reads "Well, it's too late for-")
![image](https://github.com/youkaicountry/yknytt/assets/11216597/7f358b36-bfad-494c-a667-5d7cbd8b8f39)

**Comment by up-left** [comment]
Ok, I will see how they look semi-transparent. Can't make them smaller because it will be hard to tap on them on mobiles.
