### ISSUE TITLE
juni shouldn't move forward when exiting climbing state unless you are climbing upwards

### ISSUE THREAD

**Issue by ncrecc** [youkaicountry/yknytt#176]
currently if you slide downward off a wall, or fall off a wall from gravity, juni will move slightly forward.

![yknytt_slide](https://github.com/youkaicountry/yknytt/assets/11216597/87a7c70d-14e7-4592-8061-e482b893292e)

this is incorrect behavior compared to the original game. juni should not move horizontally at all when exiting climbing, unless you are climbing upwards (hoisting yourself onto a ledge).

**Comment by up-left** [comment]
This one must be the easiest of the movement bugs you posted, I will take a look. Thank you for participation!
