### ISSUE TITLE
if skin color or shirt color is 0, it should be transparent

### ISSUE THREAD

**Issue by ncrecc** [youkaicountry/yknytt#181]
for some reason, in ks, if the custom skin color or custom shirt color is set to 0 (#000000) it will be fully transparent instead. some levels use this to intentional effect to make juni's skin/shirt color the same as whatever she's standing in front of, such as "This Is Not A Level" by Sergio Cornaga.

**Comment by up-left** [comment]
Fixed. Thanks!
