### ISSUE TITLE
collision with 1-pixel thick tiles is very buggy

### ISSUE THREAD

**Issue by ncrecc** [youkaicountry/yknytt#182]
take these clouds and angled lines from [marhide](https://nifflas.lp1.nl/index.php?topic=7381.0) (again):

![marhide collision](https://github.com/youkaicountry/yknytt/assets/11216597/d9853bd8-d03a-421b-a8eb-0553fd70ab17)

this uses default tileset 187, so it's not the case of a user adding some weird custom content

**Comment by up-left** [comment]
Yknytt relies on Godot to convert images into collision polygons, but it requires some workarounds to work. I made some changes, so it should work better.
