### ISSUE TITLE
some levels cannot be downloaded

### ISSUE THREAD

**Issue by ms2048** [youkaicountry/yknytt#187]
There are two levels that - when trying to download them - result in color red: '**david c & sergio Cornaga - Juni's Nightmare**', '**Healy - Dark Horse +**'.

Also, the level '**Raicuparta - Aperture Science**' downloads correctly but after re-entering the download level selection it is still white instead of green.

By the way, is there any particular reason for changing every space into a plus? It hurts my eyes trying to browse through all the levels and also I've tested that spaces in name of .knytt.bin file do not interfere with playing the level.

**Comment by up-left** [comment]
I removed pluses from filenames, and it started working. Thanks!
