### ISSUE TITLE
(suggestion) extend filtering options

### ISSUE THREAD

**Issue by ms2048** [youkaicountry/yknytt#188]
There are over 100 levels currently available to download (and even more on knyttlevels.com) that does not have any difficulty set. Also, I found one level (AlmightyZenTaco - Dark Sky of Wish Mountain) that has the difficulty set as 'Medium' - I suppose it is invalid but it is still there in the wild.

There are even levels without any tags at all.

My suggestion is to therefore include 'None / Other' to all the drop-down menus of all filters for level selector / downloader.

**Comment by ms2048** [comment]
(I think that separating 'None' from 'Other' would be to much options but it's just my opinion)

**Comment by up-left** [comment]
OK, that's done. But "category" popup now doesn't fit if the window size is 600:240. Can't make it smaller because it would be hard to tap items on mobiles.

**Comment by ms2048** [comment]
I would say that this is a perfect excuse to think about maybe making vertical 'freedom' when a window gets resized (on non-mobile platforms) instead of black bars, at least until entering the level. Afterwards, I suppose, a horizontal resize would seem counter intuitive - as with larger windows sometimes less levels would get visible on-screen. Sooner or later, this would need to be figured out in my opinion, as nowadays people have crazy resolutions / screen estates and not taking advantage of these in any way would be a miss.

**Comment by ms2048** [comment]
I see that you now reverted this, while still having this issue closed.

I am actively using this option, especially for the difficulty.

Could you provide any reasoning / future plans for this?

**Comment by up-left** [comment]
Still haven't decide if it necessary or not. Can't find any reason for me to use it.

**Comment by up-left** [comment]
No. I was writing messages in other threads, I didn't plan to leave it without warning.

**Comment by up-left** [comment]
There are 3 options: 1) remove these categories, 2) reduce popup item size which means it would be harder to tap on them on mobiles, 3) do some coding and support two different UI styles - for desktops and for mobiles. I chose the first option. So let this issue be closed as "won't implement".
