### ISSUE TITLE
AltF4 level broken

### ISSUE THREAD

**Issue by LumicatRB** [youkaicountry/yknytt#190]
Can't progess further, missing blocks
![Screenshot_20230903_232650_YKnytt](https://github.com/youkaicountry/yknytt/assets/143968362/ffde71e8-2c05-416a-822a-cf8d77cb96fe)

**Comment by up-left** [comment]
I repacked this level. You can uninstall it, install again, and everything should work.
For some strange reason, the original game treats some transparent tiles as solid, and I don't know why. Noticed only in this level.

**Comment by ms2048** [comment]
Trying to download this level now gives an error (red-colored bar)

**Comment by up-left** [comment]
It was a small mess with file names, fixed now
