### ISSUE TITLE
(suggestion) add map markers

### ISSUE THREAD

**Issue by ms2048** [youkaicountry/yknytt#192]
It would be very useful for larger levels to be able to mark / unmark current location on a map with... something. Like a star or even with a powerup logo. Like, umbrella for 'when you have it, come back to this place'. But even just a star or (if easier to implement) a colour change/tint for a location. I found such a feature very useful in many other metroidvania titles.

I'm not alone in this :), see https://old.reddit.com/r/metroidvania/comments/104kvi5/metroidvanias_that_let_you_write_on_or_mark_the/

**Comment by fabzenfab** [comment]
yes I confirm that. This would be really useful in big levels like Reditus or Azur Serenity for example in which you can't access certain places until you have certain power-ups or a certain number of GCs

**Comment by up-left** [comment]
I added markers in the new version, not only user ones, but also markers for unopened doors, unachieved power-ups, which are drawn on map automatically. I hope it will be useful.

**Comment by fabzenfab** [comment]
waouh génial ! thank you so much :-)
