### ISSUE TITLE
Juni's Run and Fall animations don't loop correctly

### ISSUE THREAD

**Issue by Lt-knb** [youkaicountry/yknytt#194]
Currently, the Run animation starts with the last frame of the Walk animation, for some reason.
This is the correct loop:
![Juni Fixed Yknytt Run](https://github.com/youkaicountry/yknytt/assets/87249079/6404be2c-f3b9-4523-8575-4890451c324d)

Meanwhile, the Fall animation doesn't loop correctly either.
These are the correct Intro and Loop (Intro in blue, loop in red):
![Juni Fixed Yknytt Fall](https://github.com/youkaicountry/yknytt/assets/87249079/720d45f7-8472-4231-973d-7d97325b640b)

**Comment by up-left** [comment]
OK! This one was easy.
