### ISSUE TITLE
Game closes when I open the map

### ISSUE THREAD

**Issue by fabzenfab** [youkaicountry/yknytt#203]
Hello, I would like to report a problem, it's all in the title
I'm currently playing Azur Serenity Trankil Dreams by Shreeps
Regards

**Comment by up-left** [comment]
Should be fixed in the new version.
There were some problems with very large maps, and map area of this level is 10000 * 10000 = 100 000 000 screens
But save points are still slow, taking about 2 seconds to save on my computer

**Comment by fabzenfab** [comment]
OK ;-)
