### ISSUE TITLE
Coyote time significantly less forgiving than original

### ISSUE THREAD

**Issue by Someone65** [youkaicountry/yknytt#205]
I sent a complaint in-game but I feel it requires some explanation. Define has a lot of points where blocks will disappear/move away from under you and you have to jump AFTER they do that. This is still possible in yknytt but the timing is probably 5x more difficult than it should be. The save I sent has blocks that vanish on touch which you should jump on right as you land on them which demonstrates this perfectly. Easy to get first try in vanilla Knytt.

This issue probably applies to other levels where running off a ledge and jumping immediately after you fall off is required.

As an aside, the fading pink blocks that kill you when they go solid have weird animations compared to the original. They do this strange thing with a cross effect and the timing of the fades don't look right.

**Comment by Someone65** [comment]
You can test it almost anywhere in Define that has a block that you can trigger by pressing down or anywhere with a vanish on touch block. 

[KG - Define 1.txt](https://github.com/youkaicountry/yknytt/files/15434098/KG.-.Define.1.txt)

(had to rename due to Github not allowing the .ini file extension)

**Comment by up-left** [comment]
All three issues you described were fixed:
1. Extra time to jump is also applied when Juni is just standing
2. Precise fps for custom objects
3. Juni can move while in a shift loop
If you have more, feel free to write them here!
