### ISSUE TITLE
Juni's jump near a wall is not high enough

### ISSUE THREAD

**Issue by up-left** [youkaicountry/yknytt#87]
Face any wall:
![изображение](https://user-images.githubusercontent.com/36682563/99141769-2480f580-2681-11eb-8f4e-4d4effc352ab.png)
... and try to jump in a different direction. In this example, press left, up, and S at the same time. Juni's jump will not be as high as it can be.
I've reproduced it with high jump power, but maybe it is not necessary.

**Comment by youkaicountry** [comment]
This one is strange, and might be trickier to hunt down. I will take a look at it while I am in the physics code!
