### ISSUE TITLE
Updraft doesn't give enough acceleration

### ISSUE THREAD

**Issue by up-left** [youkaicountry/yknytt#89]
Play Sky Flower in a hard mode. Reveal that this updraft cannot be passed:
![изображение](https://user-images.githubusercontent.com/36682563/99142241-c73b7300-2685-11eb-9169-4adc3c8577cf.png)
In the original game left updraft gives enough acceleration to glide to the right.

**Comment by youkaicountry** [comment]
Interesting, I have passed hard mode in YKnytt. Holding S will give more acceleration when in an updraft, which is how it can be passed, I believe.

I will test against the real game and tweak as necessary, thanks!

**Comment by up-left** [comment]
I always pass it without holding S =) Only with double jump in the last updraft.

**Comment by youkaicountry** [comment]
Okay, it does need a bit of tweaking :)

**Comment by up-left** [comment]
Additional issue about umbrella tweaking: it's impossible to reach a bird here without putting off the umbrella:
![изображение](https://user-images.githubusercontent.com/36682563/101065380-acdf2000-35c7-11eb-81ce-3f01657555f2.png)

**Comment by youkaicountry** [comment]
I'm finally going to take a look at the player physics issues.

**Comment by up-left** [comment]
Updraft works now, thanks!
But the bird is still unreachable...

**Comment by youkaicountry** [comment]
Yeah, I didn't close this issue due to reaching the bird still being a problem. What method are using to reach the bird in the actual game? Do you have the ability to upload a small recording?

**Comment by youkaicountry** [comment]
I can now reach the bird without closing the umbrella with the latest tweak.

**Comment by up-left** [comment]
A new scene for umbrella tweaking (A Knytt in Time, x989y961):
![screen6-x989y961](https://user-images.githubusercontent.com/36682563/104906756-b45f5a80-59b6-11eb-8901-3b1986b54788.png)
At first, I cannot reach this updrafts when the umbrella is on.
At second, there is an island Juni wants to reach (at x996y970), but she cannot do it in our game. She lands one screen to the left.

**Comment by youkaicountry** [comment]
Okay I will take a look at this.

**Comment by up-left** [comment]
Moved to #125
