### ISSUE TITLE
Pink color is not treated as transparent

### ISSUE THREAD

**Issue by up-left** [youkaicountry/yknytt#92]
In the original game tilesets can use pink color (#FF00FF) as transparent.

![изображение](https://user-images.githubusercontent.com/36682563/99416533-86648800-292b-11eb-81dd-0b823f521bec.png)
![изображение](https://user-images.githubusercontent.com/36682563/99417049-11de1900-292c-11eb-8b4e-67389c89a07b.png)

In this example it gives a player unnecessary ability to jump and go to the left.

**Comment by youkaicountry** [comment]
Ah. This is going to be an interesting problem to solve. 
A simple shader can probably handle it display-wise, but it also affects the physics.

Some preprocessing will need to be done on the tilesets to filter out the magenta color so that it generates the collision mesh properly.

**Comment by up-left** [comment]
![screen4](https://user-images.githubusercontent.com/36682563/104260737-a7260580-54b6-11eb-9f29-111752cb6b2f.png)

It seems that black color should also be transparent.

**Comment by up-left** [comment]
I got it, magenta is transparent for tilesets, and black is transparent for custom objects.

**Comment by youkaicountry** [comment]
I will write a color replacement routine in tileset generation. This will probably make tileset generation even slower as we will now iterate over each pixel again, but maybe it won't be so bad especially with the caching.

**Comment by youkaicountry** [comment]
I have implemented magenta -> transparent conversion for tilesets. Textures are now preprocessed before the tileset is created. Similar functionality could be implemented for loading custom objects, or the `preprocessTilesetTexture` function generalized. I'll probably close this and open another issue for custom objects.

**Comment by up-left** [comment]
Is it possible to use shaders here as you suggested earlier?
https://godotengine.org/qa/18639/how-can-i-set-any-single-color-to-be-transparent

**Comment by youkaicountry** [comment]
Shaders would handle the visuals only, unfortunately. 
Processing the collision shapes requires the CPU to know which pixels are transparent, so after examining the code I don't think there's a way to do it for this. 

The good news is that it is only slower on tilesets that have no alpha channel right now, and hopefully we won't have to change that. Writing a C extension to handle this logic might help as well, but I am hesitant to do that as it makes building the game cross-platform more of a headache. 

If this solution is too problematic that would probably be the next avenue to explore.

**Comment by youkaicountry** [comment]
Also the optimize button proposed in #120 will help greatly.

**Comment by up-left** [comment]
Got it, shaders don't affect CreateFromImageAlpha. But it is possible for customs objects. They are usually small, so I don't know yet is it worth to write this shader or use replaceColor.

**Comment by up-left** [comment]
Also this shader will be helpful to change Juni's clothes, I suppose.

**Comment by youkaicountry** [comment]
A shader will definitely be the best way to change Juni's clothing color.
